### ISSUE TITLE
Release notes within the extension

### ISSUE THREAD

**Issue by grahamperrin** [aecreations/readnext#37]
With the extension not yet at `addons.mozilla.org`, is it possible to have the _Release Notes_ tab at `about:addons`?

For now, simply link from within the tab, to <https://aecreations.io/readnext/index.php#extension-changelog>. 

Thanks

**Comment by aecreations** [comment]
This is fixed in the update manifest. The Release Notes tab will now appear for users who are updating Read Next. Note that it won't appear for those users who already have updated to version 0.8.3 before this fix was applied.

**Comment by grahamperrin** [comment]
Thanks! Close?
