### ISSUE TITLE
Feature Request: Add Left Click capability to open ReadNext sidebar links...

### ISSUE THREAD

**Issue by netarchitech** [aecreations/readnext#71]

**Comment by aecreations** [comment]
@netarchitech Can you be more specific? Left-click on what?

BTW, left-clicking on a link in the Read Next sidebar already opens the selected link in the current browser tab (assuming that the left mouse button is set as the primary button).

**Comment by netarchitech** [comment]
@aecreations Thank you for the reply and inquiry...I apologize for not being more specific...

I was referring to left-clicking on a link in the Read Next sidebar opening a new browser tab, instead of the current default behavior of opening and overwriting the contents of the current browser tab...(I am using the left mouse button set as the primary button)...

Could the desired behavior be provided as an option? Perhaps as a double-left-click on the Read Next sidebar link opening a new browser tab?

**Comment by aecreations** [comment]
You can right-click on a link in the sidebar for more options from the context menu: open in new browser tab or in a new window. If Read Next is enabled for Private Browsing mode (this can be set from Add-ons Manager), then another option is available in the context menu to open in a new Private Browsing window.

Double-clicking to open in a new browser tab is a great idea, and I'll consider it for a future release.

**Comment by netarchitech** [comment]
Thanks for the right-click/Private Browsing suggestions...I actually have been doing that since I installed your extension...Given my workflow needs, I thought I would inquire about the potential of enhancing the left-click functionality...

I am glad to read that there might be a possibility of incorporating the double-left-click/new browser tab in a future release :)
Thank you for your time, consideration, support and suggestions...I really appreciate it!

**Comment by aecreations** [comment]
Implementing a double-click action on a reading list link isn't feasible, as it is difficult to distinguish it from a single click.

Instead, the default action when clicking a link will be configurable through a new radio button option in the extension preferences page.

**Comment by aecreations** [comment]
This enhancement will be available for testing in Read Next 1.1 beta 2. Watch the blog for the beta release announcement: https://aecreations.blogspot.com/
